server:
  workers: { io: 4, cpu: 2 }
  timeouts: { header_ms: 5000, body_ms: 15000, idle_ms: 30000, write_ms: 15000 }
  limits: { header_bytes: 16384, body_bytes: 10485760, connections: 20000 }
  tls:
    enabled: false
routes: []
